[colors]
red   = "ff0000"
green = "00ff00"
blue  = "0000ff"
white = "ffffff"

# [[effect]]
# predefined = "position"
# numkeys = "pad"

[[effect]]
    [effect.input]
    property = "rpm-baseline"

    [effect.output]
    type = "meter"
    color = "red"
    fill = true

    [effect.output.keyboard]
    column = ":"
    row = "5->0"

[[effect]]
    [effect.input]
    property = "driveline"

    [effect.output]
    type = "meter"
    color = "blue"

    [effect.output.keyboard]
    column = "0->21"
    row = "1:5"

[[effect]]
    [effect.input]
    property = "speed"
    auto_raise = true

    [effect.output]
    type = "meter"
    color = "white"
    fill = true

    [effect.output.keyboard]
    column = "0->17"
    row = "0"
